services:
  - postgresql

language: node_js
node_js:
  - "5"

before_script:
  - psql postgres -c 'CREATE USER crudtest WITH PASSWORD crudtest;'
  - psql postgres -c 'CREATE DATABASE crudtest WITH OWNER crudtest;'

notifications:
  slack: devops-training-spb:H1eeLPE4mcpnrFgBfZTBtSPT